### ISSUE TITLE
Indented PHP

### ISSUE THREAD

**Issue by cesarkohl** [ajschlosser/wordpress-jade-bootstrap-template#1]
Hi,

This is not an issue but a question: how did you manage to indent PHP correctly using Jade PHP?

Thanks in advance!

Best,
Cesar

**Comment by ajschlosser** [comment]
Hi @cesarkohl,

The `gulp-jade-php` module takes an options parameter. By setting the `pretty` property to something other than `false` (which I think is the default), you can control how it formats the output. I set it to a single tab, e.g.:

``` js
.pipe(jade({
  pretty: '\t'  // Set to false to minify/uglify the PHP
}))
```

Hope that answers your question!
